apiVersion: apiserver.k8s.io/v1beta1
kind: EgressSelectorConfiguration
egressSelections:
  - name: cluster
    connection:
      proxyProtocol: GRPC
      transport:
        uds:
          udsName: /run/konnectivity-server/konnectivity.socket
