apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: slack-webhook

spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-vault

  data:
    - secretKey: address
      remoteRef:
        key: flux-system
        property: slack-webhook
