apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: speaker
  namespace: metallb-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: speaker
subjects:
- kind: ServiceAccount
  name: speaker
  namespace: metallb-system
