kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-proxy
rules:
  - apiGroups: [""]
    resources: [nodes, services]
    verbs: [get, list, watch]

  - apiGroups: [events.k8s.io]
    resources: [events]
    verbs: [create]

  - apiGroups: [discovery.k8s.io]
    resources: [endpointslices]
    verbs: [get, list, watch]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-proxy

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-proxy

subjects:
  - kind: User
    name: kube-proxy
