apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - v0.6.2

patches:
  - patch-tls-verify.yaml

patchesJson6902:
  - target:
      kind: Deployment
      name: metrics-server
    path: patch-preferred-address-types.yaml
