apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration

enableServer: true
address: 0.0.0.0
healthzBindAddress: 0.0.0.0
tlsCertFile: /etc/kubelet/server.chain
tlsPrivateKeyFile: /etc/kubelet/server.key
cgroupDriver: systemd
authentication:
  webhook:
    enabled: true
  x509:
    clientCAFile: /etc/worker/root.crt
authorization:
  mode: Webhook
resolvConf: /etc/kubelet/resolv.conf
clusterDomain: {{ cluster_domain }}
clusterDNS:
  - {{ cluster_dns }}
