- name: setup
  hosts: localhost
  connection: local
  gather_facts: no
  tags: [setup, always]
  roles:
    - role: certificate/root
      tags: [root]
      vars:
        common_name: root
        path: setup/root

- name: kube-proxy
  hosts: worker
  gather_facts: no
  become: yes
  roles:
    - role: kubectl/apply/kustomize
      vars: { path: flux/infra/kube-system/kube-proxy }

    - role: kube-proxy
