- name: setup
  hosts: localhost
  connection: local
  gather_facts: no
  tags: [setup, always]
  roles:
    - role: certificate/root
      tags: [root]
      vars:
        common_name: root
        path: setup/root

- name: node
  hosts: worker
  tags: [node, always]
  gather_facts: yes
  become: yes
  roles:
    - role: node

- name: kube-router
  hosts: worker
  gather_facts: no
  become: yes
  roles:
    - role: kubectl/apply/kustomize
      vars: { path: flux/infra/kube-system/kube-router }
      run_once: yes

    - role: kube-router
