apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: grafana

spec:
  parentRefs:
    - name: default-gateway
      namespace: istio-system

  hostnames:
    - 'grafana.yuki.no'

  rules:
    - backendRefs:
        - name: grafana
          port: 3000
