- name: Makefile
  ansible.builtin.template:
    src: metrics-server.mk
    dest: /root/Makefile.d/metrics-server.mk

- name: user
  notify: restart metrics-server
  ansible.builtin.user:
    name: metrics-server
    shell: /usr/sbin/nologin
    home: /var/lib/metrics-server
    groups: [control-plane]
    create_home: no

- name: data directory
  ansible.builtin.file:
    path: /var/lib/metrics-server
    state: directory
    owner: metrics-server
    group: metrics-server
    mode: 0750

- name: config directory
  ansible.builtin.file:
    path: /etc/metrics-server
    state: directory
    owner: metrics-server
    group: metrics-server
    mode: 0750

- name: metrics-server server certificate
  ansible.builtin.include_role:
    name: certificate/server
  vars:
    notify: restart metrics-server
    path: /etc/metrics-server/server
    chain_path: /etc/metrics-server/server.chain
    issuer: /etc/control-plane/issuer
    common_name: metrics-server
    subject_alt_names: "{{ metrics_server_subject_alt_names }}"
    owner: metrics-server

- name: metrics-server client certificate
  ansible.builtin.include_role:
    name: certificate/client
  vars:
    notify: restart metrics-server
    path: /etc/metrics-server/client
    chain_path: /etc/metrics-server/client.chain
    issuer: /etc/control-plane/issuer
    common_name: metrics-server
    organization_name: metrics-server
    owner: metrics-server

- name: metrics-server kubeconfig
  ansible.builtin.include_role:
    name: kubeconfig
  vars:
    notify: restart metrics-server
    path: /etc/metrics-server/client.kubeconfig
    certificate: /etc/metrics-server/client.chain
    key: /etc/metrics-server/client.key
    root: /etc/control-plane/root.crt
    url: "{{ apiserver_url }}"
    user: system:metrics-server
    owner: metrics-server

- name: binary
  notify: restart metrics-server
  ansible.builtin.copy:
    src: "metrics-server-{{ metrics_server_version }}-{{ node_arch }}"
    dest: /usr/bin/metrics-server
    mode: 0755

- name: service
  notify: restart metrics-server
  ansible.builtin.template:
    src: metrics-server.service
    dest: /etc/systemd/system/metrics-server.service

- name: start
  ansible.builtin.systemd:
    name: metrics-server.service
    state: started
    enabled: yes
    masked: no
    daemon_reload: yes
