apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - deployment.yaml
  - hpa.yaml
  - rbac.yaml
  - service.yaml

configMapGenerator:
  - name: coredns
    files: [Corefile]
