apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    kubernetes.io/cluster-service: "true"
  name: coredns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:coredns

rules:
  - apiGroups: [""]
    resources: [endpoints, services, pods, namespaces]
    verbs: [list, watch]

  - apiGroups: [""]
    resources: [nodes]
    verbs: [get]

  - apiGroups: [discovery.k8s.io]
    resources: [endpointslices]
    verbs: [list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:coredns

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:coredns

subjects:
  - kind: ServiceAccount
    name: coredns
