apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-token

spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-vault

  data:
    - secretKey: token
      remoteRef:
        key: flux-system
        property: github-token
