apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
  - ../../../../infra/flux/system
  - alerts
  - helm/kiali
  - monitoring

patches:
  - target:
      kind: Deployment
      name: kustomize-controller
    path: patch-requeue-dependency.yaml
