apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali

spec:
  auth:
    strategy: anonymous

  istio_namespace: istio-system

  deployment:
    namespace: istio-system

    accessible_namespaces:
      - istio-system
      - haproxy-dashboard

  istio_labels:
    app_label_name: app.kubernetes.io/name
    version_label_name: app.kubernetes.io/version
