apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: kiali

spec:
  parentRefs:
    - name: default-gateway
      namespace: istio-system

  hostnames:
    - 'kiali.yuki.no'

  rules:
    - backendRefs:
        - name: kiali
          port: 20001
