apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system

spec:
  interval: 1m
  prune: true
  path: ./flux/clusters/CLUSTER-NAME/apps
  dependsOn:
    - name: infra
  sourceRef:
    kind: GitRepository
    name: cluster
