apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cluster-repo
  namespace: flux-system

spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-vault

  dataFrom:
    - extract:
        key: flux-system/repo
