apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system

spec:
  interval: 1m
  prune: true
  path: ./flux/clusters/kyuubee
  sourceRef:
    kind: GitRepository
    name: cluster
