apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crds
  namespace: flux-system

spec:
  interval: 10m
  retryInterval: 1m
  prune: true
  path: ./flux/clusters/CLUSTER-NAME/crds
  dependsOn:
    - name: cluster
  sourceRef:
    kind: GitRepository
    name: cluster
