apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra
  namespace: flux-system

spec:
  interval: 5m
  retryInterval: 1m
  prune: true
  path: ./flux/clusters/CLUSTER-NAME/infra
  dependsOn:
    - name: crds
  sourceRef:
    kind: GitRepository
    name: cluster
