apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apps.yaml
  - cluster-repo-secret.yaml
  - cluster-repo.yaml
  - cluster.yaml
  - crds.yaml
  - infra.yaml
  - vars.yaml

replacements:
  - path: vars/cluster-name.yaml
