- name: Makefile
  ansible.builtin.template:
    src: crio.mk
    dest: /root/Makefile.d/crio.mk

- name: configure modprobe
  ansible.builtin.copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/kube.conf

- name: load modules
  loop: [overlay, br_netfilter]
  changed_when: no
  ansible.builtin.command:
    cmd: "modprobe {{ item }}"

- name: configure sysctl
  notify: restart cri
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.ip_forward
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: 1
    sysctl_file: /etc/sysctl.d/kube.conf
    reload: yes

- name: binaries
  notify: restart cri
  loop:
    - conmon
    - crio
    - pinns
  ansible.builtin.copy:
    src: "crio-{{ crio_version }}-{{ node_arch }}/{{ item }}"
    dest: /usr/bin/
    mode: 0755

- name: service
  notify: restart cri
  ansible.builtin.template:
    src: crio.service
    dest: /etc/systemd/system/crio.service

- name: "/etc/containers : directory"
  ansible.builtin.file:
    path: /etc/containers
    state: directory

- name: "/etc/containers : policy.json"
  ansible.builtin.template:
    src: policy.json
    dest: /etc/containers/policy.json

- name: kubelet override directory
  ansible.builtin.file:
    path: /etc/systemd/system/kubelet.service.d
    state: directory

- name: kubelet override
  notify: restart kubelet
  ansible.builtin.template:
    src: kubelet.conf
    dest: /etc/systemd/system/kubelet.service.d/cri.conf

- name: crictl config
  ansible.builtin.template:
    src: crictl.yaml
    dest: /etc/crictl.yaml

- name: cni config
  notify: restart cri
  ansible.builtin.template:
    src: bridge.json
    dest: /etc/cni/net.d/bridge.conflist

- name: start
  ansible.builtin.systemd:
    name: crio.service
    state: started
    enabled: yes
    masked: no
    daemon_reload: yes
