apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali-operator

spec:
  interval: 5m

  targetNamespace: kiali-operator

  install:
    createNamespace: true

  chart:
    spec:
      chart: kiali-operator
      version: 1.60.0
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: flux-system
      interval: 5m
