apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ServiceAccount--metrics-server.yaml
  - ClusterRole--system:aggregated-metrics-reader.yaml
  - ClusterRole--system:metrics-server.yaml
  - RoleBinding--metrics-server-auth-reader.yaml
  - ClusterRoleBinding--metrics-server:system:auth-delegator.yaml
  - ClusterRoleBinding--system:metrics-server.yaml
  - Service--metrics-server.yaml
  - Deployment--metrics-server.yaml
  - APIService--v1beta1.metrics.k8s.io.yaml
