apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - Namespace--metallb-system.yaml
  - ServiceAccount--controller.yaml
  - ServiceAccount--speaker.yaml
  - Role--controller.yaml
  - Role--pod-lister.yaml
  - ClusterRole--metallb-system:controller.yaml
  - ClusterRole--metallb-system:speaker.yaml
  - RoleBinding--controller.yaml
  - RoleBinding--pod-lister.yaml
  - ClusterRoleBinding--metallb-system:controller.yaml
  - ClusterRoleBinding--metallb-system:speaker.yaml
  - Secret--webhook-server-cert.yaml
  - Service--webhook-service.yaml
  - Deployment--controller.yaml
  - DaemonSet--speaker.yaml
  - ValidatingWebhookConfiguration--metallb-webhook-configuration.yaml
