apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pod-monitor.yaml

configMapGenerator:
  - name: grafana-dashboards
    files:
      - dashboards/control-plane.json
      - dashboards/cluster.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
