apiVersion: batch/v1
kind: Job
metadata:
  name: gateway-api-admission
  annotations:
  labels:
    name: gateway-api-webhook
  namespace: gateway-system
spec:
  template:
    metadata:
      name: gateway-api-admission-create
      labels:
        name: gateway-api-webhook
    spec:
      containers:
        - name: create
          image: k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1
          imagePullPolicy: IfNotPresent
          args:
            - create
            - --host=gateway-api-admission-server,gateway-api-admission-server.gateway-system.svc
            - --namespace=gateway-system
            - --secret-name=gateway-api-admission
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      restartPolicy: OnFailure
      serviceAccountName: gateway-api-admission
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
