apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - Namespace--gateway-system.yaml
  - ValidatingWebhookConfiguration--gateway-api-admission.yaml
  - Service--gateway-api-admission-server.yaml
  - Deployment--gateway-api-admission-server.yaml
  - ServiceAccount--gateway-api-admission.yaml
  - ClusterRole--gateway-api-admission.yaml
  - ClusterRoleBinding--gateway-api-admission.yaml
  - Role--gateway-api-admission.yaml
  - RoleBinding--gateway-api-admission.yaml
  - Job--gateway-api-admission.yaml
  - Job--gateway-api-admission-patch.yaml
