apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gateway-api-admission
  annotations:
  labels:
    name: gateway-api-webhook

rules:
  - apiGroups: [""]
    resources: [secrets]
    verbs: [get, create]
