apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus

spec:
  retention: 1h
  version: v2.40.5
  thanos: { version: v0.29.0 }

  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}

  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}

  serviceAccountName: prometheus

  replicas: 2

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            topologyKey: kubernetes.io/hostname

            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - prometheus
