apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-service-monitor

spec:
  selector:
    matchLabels:
      operated-prometheus: "true"

  endpoints:
    - interval: 30s
      port: web
      path: /metrics
