- include_tasks: platform/rpi-debian.yaml
  when:
    - "'rpi' in node_platform"
    - "'debian' in node_platform"

- include_tasks: platform/rpi-ubuntu.yaml
  when:
    - "'rpi' in node_platform"
    - "'ubuntu' in node_platform"

- name: group
  ansible.builtin.group:
    name: worker
    state: present

- name: config directory
  ansible.builtin.file:
    path: /etc/worker
    state: directory
    owner: root
    group: worker
    mode: 0750

- name: root certificate
  ansible.builtin.copy:
    src: setup/root.crt
    dest: /etc/worker/root.crt
    owner: root
    group: worker
    mode: 0640

- name: worker issuer
  ansible.builtin.include_role:
    name: certificate/issuer
  vars:
    common_name: worker-issuer
    path: /etc/worker/issuer
    group: worker
    owner: root
    key_mode: '0640'

