- name: cmdline.txt
  when: node_platform == 'pi'
  notify: reboot
  loop:
    - cgroup_enable=cpuset
    - cgroup_enable=memory
    - cgroup_memory=1
  ansible.builtin.replace:
    path: /boot/cmdline.txt
    regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
    replace: '\1 {{ item }}'

- name: dphys-swapfile
  when: node_platform == 'pi'
  notify: reboot
  ansible.builtin.lineinfile:
    path: /etc/dphys-swapfile
    regexp: ^CONF_SWAPSIZE
    line: CONF_SWAPSIZE=0

- name: group
  ansible.builtin.group:
    name: worker
    state: present

- name: config directory
  ansible.builtin.file:
    path: /etc/worker
    state: directory
    owner: root
    group: worker
    mode: 0750

- name: root certificate
  ansible.builtin.copy:
    src: setup/root.crt
    dest: /etc/worker/root.crt
    owner: root
    group: worker
    mode: 0640

- name: worker issuer
  ansible.builtin.include_role:
    name: certificate/issuer
  vars:
    common_name: worker-issuer
    path: /etc/worker/issuer
    group: worker
    owner: root
    key_mode: '0640'

